### ISSUE TITLE
USER STORY: Wishlist

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/Home-ish#19]
As a user, I can favourite the items I like, so that I can come back to them later when I'm ready to buy.

### Acceptance Criteria
- Create a wishlist page that only shows the user's favourites
- User must be logged in to see their favourites

### Tasks
- [ ] Add a favourite or add to wishlist link on the product detail page
- [ ] Display the user's favourites on a separate page
- [ ] Users can add to cart from their list of favourites

### Story Points Estimation
A score of 8 points
