### ISSUE TITLE
USER STORY: Buying Furniture

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/Home-ish#3]
As a renter, I want to be able to search for a variety of items that can help kit out my new home

### Acceptance Criteria
- Show a variety of items that the user can purchase from each furniture category
- Variety must show different colours and sizes
- Must have complimentary pieces to encourage the user to buy more than one item

### Tasks
- [ ] Create categories of furniture the user would most likely choose
- [ ] Show a vast range of furniture in each category
- [ ] Include options like chairs that come in sets of two or more to help the user with their decision making

### Story Points Estimation
A score of 8 points
